---
- hosts: dev
  become: true

  tasks:

  - name: Run Docker Container
    docker_container:
      name: webapp
      image: manjunathbm2003/Devops-app:latest
      state: started
      ports:
        - "8085:80"
